todo project for partner review
blakbox23/todo-partner-request pull request #1
Opened 2021-08-24 09:13 UTC by blakbox23

This is my ToDo project built as per the Microverse requirements.
Please review it for me.

2021-08-24 10:03 UTC, vikitaotiz requested changes
Reloading the browser after every addition or deletion of todo is not a good user experience. I think you should have used target parentNode to grab onto the ui elements to make it easier to make the interface reactive.

2021-08-24 10:03 UTC, vikitaotiz commented on src/crud.js
> +  window.location.reload();
Reloading the browser after every addition or deletion of todo is not a good user experience. I think you should have used target parentNode to grab onto the ui elements to make it easier to make the interface reactive.

2021-08-25 06:07 UTC, blakbox23 commented
I've fixed the KISS, DRY, and YAGNI errors. I have also reduced the number of reloads by one and now don't need to reload to add a task. any help on removing reloads while deleting would be highly appreciated.

2021-08-25 08:32 UTC, vikitaotiz approved these changes
## Approved 🥳
Keep up the good work!!!

2021-08-25 08:33 UTC, merged